method: 
  module: methods
  method: CLStrategy
  args:
    model:
      module: timm.models
      method: efficientnet_b4
      args:
        pretrained: True

    optimizer:
      module: torch.optim
      method: SGD
      args:
        lr: 0.01
    
    criterion:
      module: torch.nn
      method: CrossEntropyLoss

    plugins:
      module: class_strategy
      method: ClassStrategyPlugin
      args: 
        mem_size: 1000
        memory_transforms: [
        "transforms.RandomHorizontalFlip()",
        "transforms.RandomRotation(10)",
        "transforms.ColorJitter(brightness=0.5, hue=0.5, saturation=0.5)",
        "RandAugment()",
        "transforms.ToTensor()",
        "transforms.Normalize((0.3252, 0.3283, 0.3407), (0.0265, 0.0241, 0.0252))"]
