method: 
  module: methods
  method: CWRStar
  args:
    model:
      module: torchvision.models
      method: resnet50
      args:
        pretrained: True

    optimizer:
      module: torch.optim
      method: SGD
      args:
        lr: 0.01
    
    criterion:
      module: torch.nn
      method: CrossEntropyLoss
    cwr_layer_name: fc
    freeze_remaining_model: True