method: 
  module: methods
  method: NaiveFinetune
  args:
    model:
      module: torchvision.models
      method: resnet50
      args:
        pretrained: True

    optimizer:
      module: torch.optim
      method: SGD
      args:
        lr: 0.01
        weight_decay: 0.001
    
    criterion:
      module: torch.nn
      method: CrossEntropyLoss
